### PR TITLE
Fix building unittest

### PR DESCRIPTION
**Pull request by moetayuko**

### CODE REVIEW

**Comment by moetayuko** [comment]
@Nexarian can you take a look at this?

**Comment by Nexarian** [comment]
Some of the CI checks are failing. Fix those and otherwise it looks good.

**Comment by moetayuko** [comment]
rebased on the latest branch, the remaining errors are present in the base branch.

**Comment by Nexarian** [comment]
Ah! Fixed that :). Please rebase again.

**Comment by moetayuko** [comment]
done

**Comment by Nexarian** [comment]
Thanks for the fix :)

**Pull request merged**
